const DEFAULT_ACCESSIBLE = false;
const DEFAULT_ACCESSIBILITY_ROLE = 'none';
const DEFAULT_ACCESSIBILITY_LABEL = '';
const DEFAULT_ACCESSIBILITY_HINT = `Drag up or down to extend or minimize the list`;

export {
  DEFAULT_ACCESSIBLE,
  DEFAULT_ACCESSIBILITY_ROLE,
  DEFAULT_ACCESSIBILITY_LABEL,
  DEFAULT_ACCESSIBILITY_HINT,
};
